### ISSUE TITLE
images not displaying on feed.php

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p4-News-Aggregator#16]
I think this broke in Merge pull request #14

**Comment by ghost** [comment]
Pictures not displayed because rss does not provide image links, please read the code carefully.

**Comment by thomaskise** [comment]
It started working, so I don't know if it's really a problem.

**Comment by ghost** [comment]
`if(isset($item->children('media', true)->content)){
  				//echo 'Img: ' . $item->children('media', true)->content->attributes()['url'];
              	echo '<img src="' . $item->children('media', true)->content->attributes()['url'].'" align="middle" alt="Smiley face" height="228" width="228">';
    			$image_url = $item->children('media', true)->content->attributes()['url'];
  			}else{
    			$image_url = 'None';
  			}`
if rss provide image link, show it. if not link, none

**Comment by thomaskise** [comment]
Yeah ... I had checked about the first 10 and none were showing up.  As I
said,  it is working now.

**Comment by ghost** [comment]
In the process of catching RSS information, it is not the program writes the captured RSS stream to the database before you access it to display data on your computer. Instead, it should be you directly capture the data and display it in your browser. In this process, the program hands over the task of grabbing information to your browser instead of the remote server. The problem might be from your network, your host's network, or the host environment. I think you should repeat it a few times before suspecting the code. In addition, I conducted many tests before submitting my code just for team’s efficiency. I hope you can do the same before submitting your code. FYI, when I was checking your code, I checked my environment first before suspecting the problem actually came from the code itself.
